//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlatformKit.Internal.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlatformKit.Internal.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An invalid MacOsVersion enum value was provided..
        /// </summary>
        internal static string Exceptions_Arguments_InvalidMacOsVersionEnum {
            get {
                return ResourceManager.GetString("Exceptions.Arguments.InvalidMacOsVersionEnum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is only supported on FreeBSD..
        /// </summary>
        internal static string Exceptions_PlatformNotSupported_FreeBsdOnly {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.FreeBsdOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is not supported on legacy versions of Operating Systems. Please update your Operating System to use this feature..
        /// </summary>
        internal static string Exceptions_PlatformNotSupported_LegacyOS {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.LegacyOS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is only supported on Linux..
        /// </summary>
        internal static string Exceptions_PlatformNotSupported_LinuxOnly {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.LinuxOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is only supported on macOS..
        /// </summary>
        internal static string Exceptions_PlatformNotSupported_MacOnly {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.MacOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This functionality is only supported on Windows..
        /// </summary>
        internal static string Exceptions_PlatformNotSupported_WindowsOnly {
            get {
                return ResourceManager.GetString("Exceptions.PlatformNotSupported.WindowsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WARNING: Function not supported on Windows or macOS. Calling method using RuntimeIdentifierType.Specific instead..
        /// </summary>
        internal static string RuntimeInformation_NonLinuxSpecific_Warning {
            get {
                return ResourceManager.GetString("RuntimeInformation.NonLinuxSpecific.Warning", resourceCulture);
            }
        }
    }
}
